import js from "./js.png"
import ts from "./ts.png"
import php from "./php.png"
import sql from "./sql.png"
import nosql from "./nosql.png"
import react from "./react.png"
import native from "./native.png"
import laravel from "./laravel.png"
import vue from "./vue.png"
import express from "./express.png"
import postgres from "./postgres.png"
import mysql from "./mysql.png"
import sqlite from "./sqlite.png"
import mongo from "./mongo.png"
import html from "./html.png"
import css from "./css.png"
import tailwind from "./tailwind.png"
import rest from "./rest.png"
import git from"./git.png"
import github from "./github.png"
import docker from "./docker.png"
import n8n from "./n8n.png"
export {js,ts,php,sql, nosql, react, native, laravel, vue, express, postgres,mysql,sqlite,mongo,html,css,tailwind,rest, git, github, n8n, docker};
